// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderDemo.DataAccess.Data;

#nullable disable

namespace OrderDemo.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230329112830_AddColumn_To_OrderHeader_TotalAmount")]
    partial class AddColumn_To_OrderHeader_TotalAmount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderDemo.API.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "William"
                        },
                        new
                        {
                            Id = 2,
                            Name = "John"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sachin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Daniel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sunil"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jersy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Computer1"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Computer2"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Computer3"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Computer4"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Computer5"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Computer6"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Computer7"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Computer8"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Computer9"
                        });
                });

            modelBuilder.Entity("OrderDemo.API.Model.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12.15m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 20m,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 92.5m,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 24.25m,
                            OrderId = 4,
                            ProductId = 4,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 5,
                            Amount = 27.89m,
                            OrderId = 5,
                            ProductId = 5,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 6,
                            Amount = 610m,
                            OrderId = 6,
                            ProductId = 1,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1000.16m,
                            OrderId = 7,
                            ProductId = 2,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 8,
                            Amount = 85.74m,
                            OrderId = 8,
                            ProductId = 3,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 9,
                            Amount = 52.5m,
                            OrderId = 9,
                            ProductId = 4,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 10,
                            Amount = 66.79m,
                            OrderId = 10,
                            ProductId = 5,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 11,
                            Amount = 18.95m,
                            OrderId = 11,
                            ProductId = 1,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 12,
                            Amount = 63.67m,
                            OrderId = 12,
                            ProductId = 2,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 13,
                            Amount = 139.38m,
                            OrderId = 13,
                            ProductId = 3,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 14,
                            Amount = 138.34m,
                            OrderId = 14,
                            ProductId = 4,
                            Quantity = 2m
                        });
                });

            modelBuilder.Entity("OrderDemo.API.Model.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("OrderHeaders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            TotalAmount = 12.15m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            TotalAmount = 20m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            TotalAmount = 92.5m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            TotalAmount = 24.25m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            TotalAmount = 27.89m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            TotalAmount = 610m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            TotalAmount = 1000.16m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 8,
                            TotalAmount = 85.74m
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 10,
                            TotalAmount = 78.94m
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 10,
                            TotalAmount = 78.94m
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 11,
                            TotalAmount = 38.95m
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 12,
                            TotalAmount = 156.17m
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 13,
                            TotalAmount = 139.38m
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 14,
                            TotalAmount = 34.84m
                        });
                });

            modelBuilder.Entity("OrderDemo.API.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer",
                            Price = 50700.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "LapTop",
                            Price = 65000.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "CPU",
                            Price = 45000.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "UPS",
                            Price = 12500.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Network Switch",
                            Price = 37500.0
                        });
                });

            modelBuilder.Entity("OrderDemo.API.Model.OrderDetail", b =>
                {
                    b.HasOne("OrderDemo.API.Model.OrderHeader", "OrderHeader")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderDemo.API.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderDemo.API.Model.OrderHeader", b =>
                {
                    b.HasOne("OrderDemo.API.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderDemo.API.Model.OrderHeader", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
